# Generated by Django 5.2.6 on 2025-10-09 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("video", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ejercicio",
                "verbose_name_plural": "Ejercicios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Entrenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrenador",
                "verbose_name_plural": "Entrenadores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Atleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kilogramos",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atleta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entrenador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atletas",
                        to="core.entrenador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atleta",
                "verbose_name_plural": "Atletas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Entrenamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del entrenamiento", max_length=150
                    ),
                ),
                ("fecha", models.DateField(help_text="Fecha del entrenamiento")),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas o comentarios del entrenamiento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenamientos",
                        to="core.atleta",
                    ),
                ),
                (
                    "entrenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenamientos_creados",
                        to="core.entrenador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrenamiento",
                "verbose_name_plural": "Entrenamientos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleEntrenamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kg (opcional)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "descanso",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Descanso en segundos entre series",
                        null=True,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas adicionales sobre el ejercicio"
                    ),
                ),
                (
                    "video_atleta",
                    models.FileField(
                        blank=True,
                        help_text="Video subido por el atleta mostrando cómo realiza el ejercicio",
                        null=True,
                        upload_to="videos_atletas/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_entrenamientos",
                        to="core.ejercicio",
                    ),
                ),
                (
                    "entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_ejercicios",
                        to="core.entrenamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Entrenamiento",
                "verbose_name_plural": "Detalles de Entrenamientos",
                "ordering": ["entrenamiento", "ejercicio"],
            },
        ),
        migrations.CreateModel(
            name="SerieEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_serie",
                    models.PositiveIntegerField(
                        help_text="Número de la serie dentro del ejercicio"
                    ),
                ),
                (
                    "repeticiones_o_rango",
                    models.CharField(
                        help_text="Repeticiones (e.g., '10') o Rango (e.g., '8-12')",
                        max_length=20,
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kg de la serie (puede ser distinto por serie)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "detalle_entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="core.detalleentrenamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serie de Ejercicio",
                "verbose_name_plural": "Series de Ejercicios",
                "ordering": ["detalle_entrenamiento", "numero_serie"],
            },
        ),
    ]
