# Generated by Django 5.2.6 on 2025-10-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serieejercicio",
            name="peso_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="El peso exacto levantado por el atleta.",
                max_digits=5,
                null=True,
                verbose_name="Peso Levantado (Kg)",
            ),
        ),
        migrations.AddField(
            model_name="serieejercicio",
            name="repeticiones_reales",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de repeticiones que el atleta completó.",
                null=True,
                verbose_name="Repeticiones Realizadas",
            ),
        ),
    ]
