# Generated by Django 5.2.6 on 2025-10-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_serieejercicio_peso_real_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrenamiento",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Entrenamiento",
                "verbose_name_plural": "Entrenamientos",
            },
        ),
        migrations.AlterField(
            model_name="entrenamiento",
            name="fecha",
            field=models.DateField(
                blank=True, help_text="Fecha de creación o día sugerido", null=True
            ),
        ),
        migrations.AlterField(
            model_name="serieejercicio",
            name="peso",
            field=models.CharField(
                blank=True,
                help_text="Peso en kg (ej: '100' o '-')",
                max_length=10,
                null=True,
            ),
        ),
    ]
