# Generated by Django 5.2.6 on 2025-10-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_entrenamiento_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrenador",
            name="user",
        ),
        migrations.RemoveField(
            model_name="detalleentrenamiento",
            name="descanso",
        ),
        migrations.RemoveField(
            model_name="detalleentrenamiento",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="entrenamiento",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="serieejercicio",
            name="peso",
        ),
        migrations.AddField(
            model_name="detalleentrenamiento",
            name="peso_recomendado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso recomendado por el entrenador (kg)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entrenamiento",
            name="ejercicios",
            field=models.ManyToManyField(
                related_name="entrenamientos",
                through="core.DetalleEntrenamiento",
                to="core.ejercicio",
            ),
        ),
        migrations.AddField(
            model_name="serieejercicio",
            name="entrenamiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="core.entrenamiento",
            ),
        ),
        migrations.AlterField(
            model_name="detalleentrenamiento",
            name="ejercicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="core.ejercicio",
            ),
        ),
        migrations.AlterField(
            model_name="detalleentrenamiento",
            name="entrenamiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="core.entrenamiento",
            ),
        ),
        migrations.AlterField(
            model_name="detalleentrenamiento",
            name="notas",
            field=models.TextField(
                blank=True, help_text="Notas específicas sobre el ejercicio"
            ),
        ),
        migrations.AlterField(
            model_name="detalleentrenamiento",
            name="video_atleta",
            field=models.FileField(
                blank=True,
                help_text="Video subido por el atleta ejecutando el ejercicio",
                null=True,
                upload_to="videos_atletas/",
            ),
        ),
        migrations.AlterField(
            model_name="serieejercicio",
            name="peso_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Peso levantado (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="serieejercicio",
            name="repeticiones_o_rango",
            field=models.CharField(
                help_text="Repeticiones o rango (ej: '10' o '8-12')", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="serieejercicio",
            name="repeticiones_reales",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Repeticiones realizadas"
            ),
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrenador", "Entrenador"), ("atleta", "Atleta")],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kilogramos (solo atletas)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "entrenador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entrenador asignado (solo para atletas)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atletas",
                        to="core.perfilusuario",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="entrenamiento",
            name="atleta",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "atleta"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entrenamientos",
                to="core.perfilusuario",
            ),
        ),
        migrations.AlterField(
            model_name="entrenamiento",
            name="entrenador",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "entrenador"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entrenamientos_creados",
                to="core.perfilusuario",
            ),
        ),
        migrations.DeleteModel(
            name="Atleta",
        ),
        migrations.DeleteModel(
            name="Entrenador",
        ),
    ]
