# Generated by Django 5.2.6 on 2025-10-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_entrenador_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detalleentrenamiento",
            options={
                "ordering": ["entrenamiento", "orden"],
                "verbose_name": "Detalle de Entrenamiento",
                "verbose_name_plural": "Detalles de Entrenamientos",
            },
        ),
        migrations.AddField(
            model_name="detalleentrenamiento",
            name="orden",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Posición del ejercicio en la rutina (1, 2, 3...)",
            ),
        ),
    ]
