# Generated by Django 5.2.6 on 2026-02-26 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_detalleentrenamiento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrenamiento",
            name="dia_orden",
            field=models.PositiveIntegerField(
                default=1, help_text="Orden de la sesión en la semana (1, 2, 3...)"
            ),
        ),
        migrations.AddField(
            model_name="entrenamiento",
            name="semana",
            field=models.PositiveIntegerField(
                default=1, help_text="Número de semana dentro del mesociclo"
            ),
        ),
        migrations.AddField(
            model_name="serieejercicio",
            name="rpe_prescrito",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="RPE Objetivo (ej: 8, 9)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serieejercicio",
            name="rpe_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="RPE Real",
            ),
        ),
        migrations.AlterField(
            model_name="serieejercicio",
            name="numero_serie",
            field=models.PositiveIntegerField(help_text="Número de la serie"),
        ),
        migrations.AlterField(
            model_name="serieejercicio",
            name="repeticiones_o_rango",
            field=models.CharField(help_text="Ej: '10' o '8-12'", max_length=20),
        ),
        migrations.CreateModel(
            name="Mesociclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Bloque Hipertrofia - Enero", max_length=150
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "semanas_objetivo",
                    models.PositiveIntegerField(
                        default=4, help_text="Duración planeada en semanas"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, aparece en el dashboard",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "atleta",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "atleta"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesociclos",
                        to="core.perfilusuario",
                    ),
                ),
                (
                    "entrenador",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "entrenador"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesociclos_creados",
                        to="core.perfilusuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesociclo",
                "verbose_name_plural": "Mesociclos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="entrenamiento",
            name="mesociclo",
            field=models.ForeignKey(
                blank=True,
                help_text="Bloque al que pertenece este entreno",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entrenamientos",
                to="core.mesociclo",
            ),
        ),
    ]
