# Generated by Django 5.2.6 on 2026-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_entrenamiento_dia_orden_entrenamiento_semana_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesociclo",
            name="objetivo",
            field=models.CharField(
                blank=True,
                help_text="Objetivo principal (ej: Ganar Fuerza)",
                max_length=200,
            ),
        ),
    ]
